// UI labels only. Imported music titles and channel names keep their original language.
export const updatesCopy={
 en:{
  '좌우 ASMR 플레이어':'Dual ASMR player',
  '목록의 곡을 담고 재생 · 최대 500곡':'Add playlist songs and play · up to 500 songs',
  '월드컵에 사용할 저장된 재생목록':'Saved playlist for the tournament',
  '관리자 확인됨':'Admin verified','확인 중':'Checking','2차는 수동으로만 실행합니다.':'Secondary sync runs manually only.',
  '개 목록':' playlists','개 링크':' links','강':' songs','현재 상태:':'Status:','잠김':'Locked','열림':'Unlocked','다음 자동 갱신: 관리자 접속 시':'Next automatic update: on admin visit',
  '1차 큐레이션':'Primary curation','2차 월별·연간 수집':'Secondary collections','진행 기록':'progress log','동기화 로그 ·':'Sync log ·','1차':'Stage 1','2차':'Stage 2','· 최근 12개':'· latest 12',
"100개씩 가볍게 표시해요. 저장된 사진이 없는 채널은 이름의 첫 글자로 표시합니다.":"Shown in pages of 100. Channels without a saved photo use their initial.","로그인 없이 남기는 작은 추천함이에요. 최신 추천만 가볍게 보여줍니다.":"A small recommendation box, with no login required. Only recent recommendations are shown.","그 노래, 어디 있었더라.":"Where did I hear that song?","같은 영상은 한 번만 표시하고 소속 목록은 함께 남겨요.":"Each video appears once, with all its playlists.","검색할 곡 정보를 불러오는 중…":"Loading searchable songs…","Python으로 쓰던 링크 추출기를 웹 안으로 옮겼어요. 공유하고 싶은 재생목록 주소를 붙여넣으면 저장하지 않고 영상 단축 링크만 꺼냅니다.":"Paste a playlist URL to extract short video links for sharing, without saving the playlist.","저장된 재생목록에서 고르기":"Choose a saved playlist","재생목록 링크를 붙여넣어 주세요.":"Paste a playlist URL.","월드컵 만들기":"Create a tournament","한 곡.":"One song.","내 재생목록으로 시작하는 음악 이상형 월드컵":"A music tournament from your playlist","재생목록 가져오기":"Load playlist","공개 또는 일부 공개 재생목록을 사용할 수 있어요.":"Public or unlisted playlists are supported.","재생목록을 먼저 가져와 주세요":"Load a playlist first","유튜브 재생목록 링크를 넣으면 준비 상태가 표시돼요.":"Paste a YouTube playlist URL to check its readiness.","몇 강으로 시작할까요?":"Choose the tournament size","다른 대진 규모":"Other tournament sizes","재생목록을 넣고":"Load a playlist","더 좋아하는 곡을 고르면":"Choose the song you prefer","나의 우승곡이 전체 랭킹에":"Your winner joins the ranking","새로운 음악을 들여오는 곳.":"Bring new music into the room.","한 번 연결한 채널은 다음 달에도 그대로.":"Your connected channel stays ready for next month.","관리 잠금":"Admin lock","관리자 키":"Admin key","잠금 닫기":"Lock management","현재 상태: 잠김":"Status: Locked","현재 상태: 열림":"Status: Unlocked","보관실에 직접 추가, 삭제, JSON/CSV 갱신은 관리자 키가 있어야 실행돼요. 방문자용 링크 추출과 월드컵 불러오기는 저장 없이 일회성으로만 작동합니다.":"Adding, deleting and updating JSON/CSV requires admin access. Visitor link tools and tournaments are temporary.","전체 동기화와 실패 목록 재시도는 관리 잠금을 연 뒤 사용할 수 있어요. 1차는 관리자 접속 시 하루 한 번 자동 갱신합니다. 최신 월의 픽만 갱신은 누구나 사용할 수 있어요. 2차는 202X.XX와 연간 수집 목록·A bundle of songs를 아래 버튼으로 선택했을 때만 가져옵니다. 저장된 기존 자료는 그대로 이용할 수 있어요.":"Full sync and retries require admin access. Primary sync runs daily on admin visits. Anyone can refresh the latest monthly Pick. Secondary collections are imported manually using the button below; saved music remains available.","2차 월별·연간 수집 동기화 (대용량)":"Secondary collection sync (large)","1차 기록":"Primary log","2차 기록":"Secondary log","1차 큐레이션 진행 기록":"Primary curation progress","2차 수집 진행 기록":"Secondary collection progress","동기화 중단":"Stop sync","사용자가 동기화를 중단했어요. 남은 목록은 이어서 가져올 수 있어요.":"Sync stopped. The remaining queue can be resumed.","이번 확인에서 건너뛴 목록:":"Skipped in this run:","다음 자동 갱신:":"Next automatic update:","관리자 접속 시":"On admin visit","선택 단계 마지막 성공:":"Last successful sync for this stage:","링크로 직접 가져오기":"Import from a link","아직 기록이 없어요.":"No logs yet.","자료별 DB 초기화":"Reset each data source","저장된 재생목록과 표지, 동기화 기록을 비웁니다. JSON·CSV 채널 자료와 월드컵 기록, 곡추천 병은 유지돼요.":"Clear saved playlists, covers and sync logs. JSON/CSV channel data, tournaments and song recommendations are retained.","최신 월의 픽 갱신과 기록 조회는 누구나 이용하며, 전체 동기화·재시도·중단과 수동 추가·삭제·초기화는 관리자 전용입니다. 방문자가 링크를 넣어 쓰는 기능은 저장하지 않고 그 자리에서만 사용합니다.":"Anyone can refresh the latest monthly Pick and read logs. Full sync, retries, stopping, adding, deleting and resetting require admin access. Visitor link tools do not save to the archive.","조건에 맞는 확인된 곡이 없어요. 조건을 넓혀 주세요.":"No verified songs match. Try broader filters.","YouTube Subscription Manager JSON 업로드":"Upload YouTube Subscription Manager JSON","가져오기 · 동기화에서 관리 잠금을 열어 주세요.":"Unlock admin access in Import · Sync.",

"나의 음악 보관실":"My music room","프로젝트 선택":"Choose a project","언어 선택":"Choose language","사이트 공유 링크 복사":"Copy site link","알림 닫기":"Dismiss notice","오류 닫기":"Dismiss error","전체 메뉴":"Menu","마지막에 남을 한 곡은?":"Which song will win?","곡의 서로 다른 발견":"unique songs discovered","전체 큐레이션":"All curated playlists","그 밖의 큐레이션":"Other curated playlists","큐레이션":"Curated","수집 목록":"Collections","기간":"Period","제목":"Title","갱신일":"Updated","재생목록 정렬 기준":"Playlist sort order","정렬 방향":"Sort direction","전체 연도":"All years","전체 월":"All months","다른 재생목록 뽑기":"Pick another playlist","곡":" songs","곡 ·":" songs ·","조회수 미제공":"Views unavailable","음악을 모으고, 취향을 이어가는 공간.":"Collect music, connect your taste.","월의 픽 · 큐레이션":"Monthly Picks · curated","한 달 동안 다시 듣고 선별한 재생목록":"Playlists replayed and curated throughout the month","월별·연간 수집 목록":"Monthly and annual collections","202X.XX · a bundle of songs · 들었던 곡을 다시 찾는 보관함":"202X.XX · a bundle of songs · Revisit collected songs","구독목록에서 랜덤 채널 찾기":"Random channels from subscriptions","페이지":"Page","개":"items","채널에서 음악 찾아보기":"Discover music on this channel","채널 열기":"Open channel","조건을 정하고 음악을 뽑아보세요.":"Set filters and pick songs.","YouTube 재생목록 주소":"YouTube playlist URL","구독목록 CSV 업로드":"Upload subscriptions CSV","올바른 YouTube 영상 링크를 입력해 주세요.":"Enter a valid YouTube video URL.","요청 간격을 지키고 있어요. 잠시 후 남은 목록을 이어서 가져와 주세요.":"Waiting between requests. Resume the remaining playlists shortly.","듣고 싶은 음악, 해보고 싶은 프로젝트를 골라보세요.":"Choose music or a project to explore.","soteria_room · 링크 프로필":"soteria_room · Link profile",

  '분류된 목록':'Organized playlists','자극적인 카와보 플리들':'Bold Kawaii Voice playlists',
  '노래 제목, 채널 이름, 재생목록 이름으로 모든 곡을 찾아요.':'Search all songs by song title, channel or playlist.',
  '추천 커버곡 찾기에 좋습니다.':'Great for discovering recommended covers.',
  '유튜브 재생목록 링크 입력 후 불러오기 클릭':'Paste a YouTube playlist URL, then click Load',
  '영상의 썸네일 최대 화질로 다운받기':'Download the best available video thumbnail',
  '전체 채널 보관실.':'All-channel archive.','전체 채널 보관실':'All-channel archive',
  '태그별 채널을 둘러보고, 확장 프로그램 JSON으로 주기적으로 갱신해요.':'Browse channels by tag. Extension JSON keeps the archive up to date.',
  '받을 사람에게 전할 짧은 메모':'A short note for the recipient',
  '관리자 전용 기능입니다.':'Admins only.',
  '관리자 전용 기능입니다. 관리 잠금을 열면 재생목록을 보관실에 추가할 수 있어요.':'Admins can unlock management to add playlists to the archive.',
  '모아둔 음악과 덜 알려진 채널을 발견해요.':'Discover collected music and smaller channels.',
  '한 번에 2개씩 순차로 가져와요. 남은 목록은 다음 실행에서 이어집니다.':'Import two playlists per run, one at a time. The next run resumes the queue.',
  '링크를 붙이면 영상 제목과 채널 이름을 자동으로 가져와요.':'Paste a link to fill in the video title and channel name automatically.',
  '영상 정보를 확인하는 중…':'Checking video information…',
  '영상 제목과 채널 이름을 가져왔어요. 필요하면 수정하세요.':'Video title and channel name filled in. Edit them if needed.',
  '영상 정보를 가져오지 못했어요. 제목과 아티스트를 직접 입력할 수 있어요.':'Could not read video information. Enter the title and artist manually.',
  '영상 제목을 확인하지 못했어요.':'Could not read the video title.',
  '관리 잠금을 먼저 열어 주세요.':'Unlock management first.',
  '임시 듣기 목록':'Temporary listening queue','화면 모드':'Player mode','화면 모드 선택':'Choose player mode',
  '전체 모드':'Full mode','기본 모드':'Default mode','미니 모드':'Mini mode',
  '재생 설정 닫기':'Close player settings','재생 설정':'Player settings','듣기 목록 접기':'Collapse queue','듣기 목록 펼치기':'Expand queue',
  '10초 뒤로':'Back 10 seconds','10초 앞으로':'Forward 10 seconds','재생 위치':'Playback position',
  '플레이어 닫기':'Close player','일시정지':'Pause','볼륨':'Volume','셔플':'Shuffle',
  '앰비언트 강도':'Ambient intensity','앰비언트 강도 ·':'Ambient intensity ·',
  '재생 불가 영상 건너뛰기':'Skip unavailable videos',
  '화질은 YouTube 재생기의 설정에서 조절할 수 있어요.':'Adjust video quality in the YouTube player settings.',
  '목록 비우기':'Clear queue','이 브라우저에서 잠깐 듣는 목록 · 새로고침하면 비워져요.':'A temporary queue in this browser · clears on refresh.',
  '채널 뽑기 결과':'Channel draw results','구독 채널 검색':'Search subscribed channels','전체 구독 채널 페이지':'Subscription list pages',
  '저장된':'Saved','개 채널 안에서 뽑아요. 구독자 수 기준의 필터는 적용하지 않아요.':'channels to pick from. Subscriber filters do not apply.',
  '아직 없음':'Not yet','마지막 가져오기:':'Last import:','기본 데이터':'Built-in data','초기화됨':'Cleared',
  '메이저 남':'Mainstream male','우타이테 남':'Male utaite','메이저 여':'Mainstream female','우타이테 여':'Female utaite','작곡가':'Composers','토픽':'Topic','플레이리스트':'Playlists','일본':'Japan','한국':'Korea',
 },
 ja:{
  '좌우 ASMR 플레이어':'左右ASMRプレーヤー',
  '목록의 곡을 담고 재생 · 최대 500곡':'曲をリストに追加して再生・最大500曲',
  '월드컵에 사용할 저장된 재생목록':'トーナメント用の保存済みプレイリスト',
  '관리자 확인됨':'管理者確認済み','확인 중':'確認中','2차는 수동으로만 실행합니다.':'2次同期は手動のみです。',
  '개 목록':'件のプレイリスト','개 링크':'件のリンク','강':'曲','현재 상태:':'状態：','잠김':'ロック中','열림':'解除済み','다음 자동 갱신: 관리자 접속 시':'次の自動更新：管理者のアクセス時',
  '1차 큐레이션':'1次キュレーション','2차 월별·연간 수집':'2次月別・年別収集','진행 기록':'進行記録','동기화 로그 ·':'同期記録・','1차':'第1段階','2차':'第2段階','· 최근 12개':'・直近12件',
"100개씩 가볍게 표시해요. 저장된 사진이 없는 채널은 이름의 첫 글자로 표시합니다.":"100件ずつ表示します。写真がないチャンネルは名前の頭文字で表示します。","로그인 없이 남기는 작은 추천함이에요. 최신 추천만 가볍게 보여줍니다.":"ログイン不要の小さなおすすめ箱です。最新のおすすめを表示します。","그 노래, 어디 있었더라.":"あの曲、どこで聴いたっけ。","같은 영상은 한 번만 표시하고 소속 목록은 함께 남겨요.":"同じ動画は一度だけ表示し、収録プレイリストをまとめます。","검색할 곡 정보를 불러오는 중…":"検索用の曲情報を読み込み中…","Python으로 쓰던 링크 추출기를 웹 안으로 옮겼어요. 공유하고 싶은 재생목록 주소를 붙여넣으면 저장하지 않고 영상 단축 링크만 꺼냅니다.":"プレイリストのリンクから共有用の短縮動画リンクを抽出します。保管室には保存しません。","저장된 재생목록에서 고르기":"保存済みプレイリストから選ぶ","재생목록 링크를 붙여넣어 주세요.":"プレイリストのリンクを貼ってください。","월드컵 만들기":"トーナメントを作る","한 곡.":"一曲。","내 재생목록으로 시작하는 음악 이상형 월드컵":"自分のプレイリストで始める音楽トーナメント","재생목록 가져오기":"プレイリストを読み込む","공개 또는 일부 공개 재생목록을 사용할 수 있어요.":"公開・限定公開プレイリストを利用できます。","재생목록을 먼저 가져와 주세요":"先にプレイリストを読み込んでください","유튜브 재생목록 링크를 넣으면 준비 상태가 표시돼요.":"YouTubeプレイリストのリンクを入力すると準備状態が表示されます。","몇 강으로 시작할까요?":"何曲で始めますか？","다른 대진 규모":"その他の対戦数","재생목록을 넣고":"プレイリストを入れて","더 좋아하는 곡을 고르면":"好きな曲を選ぶと","나의 우승곡이 전체 랭킹에":"優勝曲が全体ランキングへ","새로운 음악을 들여오는 곳.":"新しい音楽を迎える場所。","한 번 연결한 채널은 다음 달에도 그대로.":"接続したチャンネルは来月もそのまま。","관리 잠금":"管理ロック","관리자 키":"管理者キー","잠금 닫기":"管理ロックを閉じる","현재 상태: 잠김":"状態：ロック中","현재 상태: 열림":"状態：解除済み","보관실에 직접 추가, 삭제, JSON/CSV 갱신은 관리자 키가 있어야 실행돼요. 방문자용 링크 추출과 월드컵 불러오기는 저장 없이 일회성으로만 작동합니다.":"追加・削除・JSON/CSV更新には管理者キーが必要です。閲覧者のリンク抽出とトーナメントは一時利用です。","전체 동기화와 실패 목록 재시도는 관리 잠금을 연 뒤 사용할 수 있어요. 1차는 관리자 접속 시 하루 한 번 자동 갱신합니다. 최신 월의 픽만 갱신은 누구나 사용할 수 있어요. 2차는 202X.XX와 연간 수집 목록·A bundle of songs를 아래 버튼으로 선택했을 때만 가져옵니다. 저장된 기존 자료는 그대로 이용할 수 있어요.":"全体同期・再試行は管理者専用です。1次は管理者のアクセス時に1日1回確認します。最新の月のPickは誰でも更新できます。2次の月別・年別収集は下のボタンで手動取得します。保存済みの音楽は引き続き利用できます。","2차 월별·연간 수집 동기화 (대용량)":"2次 月別・年別収集の同期（大容量）","1차 기록":"1次の記録","2차 기록":"2次の記録","1차 큐레이션 진행 기록":"1次キュレーションの進行記録","2차 수집 진행 기록":"2次収集の進行記録","동기화 중단":"同期を停止","사용자가 동기화를 중단했어요. 남은 목록은 이어서 가져올 수 있어요.":"同期を停止しました。残りは再開できます。","이번 확인에서 건너뛴 목록:":"今回スキップした一覧：","다음 자동 갱신:":"次の自動更新：","관리자 접속 시":"管理者のアクセス時","선택 단계 마지막 성공:":"この段階の最終成功：","링크로 직접 가져오기":"リンクから直接取得","아직 기록이 없어요.":"まだ記録がありません。","자료별 DB 초기화":"データ別の初期化","저장된 재생목록과 표지, 동기화 기록을 비웁니다. JSON·CSV 채널 자료와 월드컵 기록, 곡추천 병은 유지돼요.":"プレイリスト・表紙・同期記録を消去します。JSON/CSVのチャンネル情報、トーナメント、曲のおすすめは残ります。","최신 월의 픽 갱신과 기록 조회는 누구나 이용하며, 전체 동기화·재시도·중단과 수동 추가·삭제·초기화는 관리자 전용입니다. 방문자가 링크를 넣어 쓰는 기능은 저장하지 않고 그 자리에서만 사용합니다.":"最新の月のPick更新と記録閲覧は誰でも利用できます。全体同期・再試行・停止・追加・削除・初期化は管理者専用です。閲覧者のリンク入力は保管室に保存されません。","조건에 맞는 확인된 곡이 없어요. 조건을 넓혀 주세요.":"条件に合う確認済みの曲がありません。条件を広げてください。","YouTube Subscription Manager JSON 업로드":"YouTube Subscription ManagerのJSONをアップロード","가져오기 · 동기화에서 관리 잠금을 열어 주세요.":"インポート・同期で管理ロックを解除してください。",

"나의 음악 보관실":"私の音楽保管室","프로젝트 선택":"プロジェクトを選択","언어 선택":"言語を選択","사이트 공유 링크 복사":"サイトリンクをコピー","알림 닫기":"お知らせを閉じる","오류 닫기":"エラーを閉じる","전체 메뉴":"メニュー","마지막에 남을 한 곡은?":"最後に残る一曲は？","곡의 서로 다른 발견":"曲との出会い","전체 큐레이션":"すべてのキュレーション","그 밖의 큐레이션":"その他のキュレーション","큐레이션":"キュレーション","수집 목록":"収集リスト","기간":"期間","제목":"タイトル","갱신일":"更新日","재생목록 정렬 기준":"プレイリストの並べ方","정렬 방향":"並べる方向","전체 연도":"すべての年","전체 월":"すべての月","다른 재생목록 뽑기":"別のプレイリストを選ぶ","곡":"曲","곡 ·":"曲 ·","조회수 미제공":"再生数非公開","음악을 모으고, 취향을 이어가는 공간.":"音楽を集め、好みをつなぐ場所。","월의 픽 · 큐레이션":"月のPick・キュレーション","한 달 동안 다시 듣고 선별한 재생목록":"ひと月を通して聴き、選んだプレイリスト","월별·연간 수집 목록":"月別・年別の収集リスト","202X.XX · a bundle of songs · 들었던 곡을 다시 찾는 보관함":"202X.XX・a bundle of songs・聴いた曲を探す保管室","구독목록에서 랜덤 채널 찾기":"登録一覧からチャンネルをランダムに探す","페이지":"ページ","개":"件","채널에서 음악 찾아보기":"チャンネルで音楽を探す","채널 열기":"チャンネルを開く","조건을 정하고 음악을 뽑아보세요.":"条件を決めて曲を選ぼう。","YouTube 재생목록 주소":"YouTubeプレイリストURL","구독목록 CSV 업로드":"登録一覧CSVをアップロード","올바른 YouTube 영상 링크를 입력해 주세요.":"正しいYouTube動画リンクを入力してください。","요청 간격을 지키고 있어요. 잠시 후 남은 목록을 이어서 가져와 주세요.":"取得の間隔を空けています。しばらくして残りを再開してください。","듣고 싶은 음악, 해보고 싶은 프로젝트를 골라보세요.":"聴きたい音楽や使いたい機能を選ぼう。","soteria_room · 링크 프로필":"soteria_room・リンクプロフィール",

  '분류된 목록':'分類済みのプレイリスト','자극적인 카와보 플리들':'刺激的なカワボプレイリスト',
  '노래 제목, 채널 이름, 재생목록 이름으로 모든 곡을 찾아요.':'曲名・チャンネル名・プレイリスト名で全曲を検索できます。',
  '추천 커버곡 찾기에 좋습니다.':'おすすめのカバー曲探しにもどうぞ。',
  '유튜브 재생목록 링크 입력 후 불러오기 클릭':'YouTubeプレイリストのリンクを入力して「読み込む」を押してください',
  '영상의 썸네일 최대 화질로 다운받기':'動画のサムネイルを最高画質でダウンロード',
  '전체 채널 보관실.':'全チャンネルの保管室。','전체 채널 보관실':'全チャンネルの保管室',
  '태그별 채널을 둘러보고, 확장 프로그램 JSON으로 주기적으로 갱신해요.':'タグ別にチャンネルを探し、拡張機能のJSONで定期的に更新します。',
  '받을 사람에게 전할 짧은 메모':'受け取る人にひとこと',
  '관리자 전용 기능입니다.':'管理者専用です。',
  '관리자 전용 기능입니다. 관리 잠금을 열면 재생목록을 보관실에 추가할 수 있어요.':'管理者がロックを解除すると、保管室にプレイリストを追加できます。',
  '모아둔 음악과 덜 알려진 채널을 발견해요.':'集めた音楽と、まだ知られていないチャンネルに出会おう。',
  '한 번에 2개씩 순차로 가져와요. 남은 목록은 다음 실행에서 이어집니다.':'1回につき2件を順番に取得します。残りは次の実行で再開します。',
  '링크를 붙이면 영상 제목과 채널 이름을 자동으로 가져와요.':'リンクを貼ると動画タイトルとチャンネル名が自動入力されます。',
  '영상 정보를 확인하는 중…':'動画情報を確認中…',
  '영상 제목과 채널 이름을 가져왔어요. 필요하면 수정하세요.':'動画タイトルとチャンネル名を入力しました。必要に応じて修正してください。',
  '영상 정보를 가져오지 못했어요. 제목과 아티스트를 직접 입력할 수 있어요.':'動画情報を取得できませんでした。タイトルとアーティストを直接入力できます。',
  '영상 제목을 확인하지 못했어요.':'動画タイトルを確認できませんでした。',
  '관리 잠금을 먼저 열어 주세요.':'先に管理ロックを解除してください。',
  '임시 듣기 목록':'一時再生リスト','화면 모드':'表示モード','화면 모드 선택':'表示モードを選択',
  '전체 모드':'全体モード','기본 모드':'通常モード','미니 모드':'ミニモード',
  '재생 설정 닫기':'再生設定を閉じる','재생 설정':'再生設定','듣기 목록 접기':'再生リストを折りたたむ','듣기 목록 펼치기':'再生リストを開く',
  '10초 뒤로':'10秒戻す','10초 앞으로':'10秒進める','재생 위치':'再生位置',
  '플레이어 닫기':'プレイヤーを閉じる','일시정지':'一時停止','볼륨':'音量','셔플':'シャッフル',
  '앰비언트 강도':'アンビエントの強さ','앰비언트 강도 ·':'アンビエントの強さ ·',
  '재생 불가 영상 건너뛰기':'再生できない動画をスキップ',
  '화질은 YouTube 재생기의 설정에서 조절할 수 있어요.':'画質はYouTubeプレイヤーの設定で変更できます。',
  '목록 비우기':'再生リストを空にする','이 브라우저에서 잠깐 듣는 목록 · 새로고침하면 비워져요.':'このブラウザーの一時リスト · 再読み込みで消去されます。',
  '채널 뽑기 결과':'チャンネル抽選結果','구독 채널 검색':'登録チャンネルを検索','전체 구독 채널 페이지':'登録チャンネル一覧のページ',
  '저장된':'保存済み','개 채널 안에서 뽑아요. 구독자 수 기준의 필터는 적용하지 않아요.':'チャンネルから選びます。登録者数フィルターは使いません。',
  '아직 없음':'まだありません','마지막 가져오기:':'最終取得:','기본 데이터':'内蔵データ','초기화됨':'初期化済み',
  '메이저 남':'メジャー男性','우타이테 남':'男性歌い手','메이저 여':'メジャー女性','우타이테 여':'女性歌い手','작곡가':'作曲家','토픽':'トピック','플레이리스트':'プレイリスト','일본':'日本','한국':'韓国',
 }
};
